[package]
name = "dis-rs"
version = "0.8.0"
authors = ["Zeeger Lubsen <zeeger@lubsen.eu>"]
description = """
An implementation of the Distributed Interactive Simulation protocol in Rust.

This main crate contains PDU implementations and facilities to read/write PDUs
from Rust data structures to the wire format and vice versa.
"""
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/zlubsen/dis-rs/dis_lib"
categories = ["network-programming"]
keywords = ["simulation", "DIS"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
bytes = "1.4.0"
nom = "7.1.3"

[build-dependencies]
quote = "1.0.26"
quick-xml = "0.28.0"
proc-macro2 = "1.0.52"