[package]
name = "cdis-assemble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dis-rs = { path = "../dis-rs" }
bytes = "1.4.0"
nom = "7.1.3"
bitvec = "1.0.1"
num = "0.4.1"