[package]
name = "cdis-gateway"
version = "0.1.0"
authors = ["Zeeger Lubsen <zeeger@lubsen.eu>"]
description = """
A gateway for the Compressed-Distributed Interactive Simulation protocol.

The gateway encodes/decodes DIS PDUs to/from C-DIS.
"""
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/zlubsen/dis-rs"
categories = ["network-programming"]
keywords = ["simulation", "DIS", "C-DIS", "gateway", "CLI"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
dis-rs = { path = "../dis-rs" }
cdis-assemble = { path = "../cdis-assemble" }