[package]
name = "cdis-gateway"
version = "0.1.0"
authors = ["Zeeger Lubsen <zeeger@lubsen.eu>"]
description = """
A gateway for the Compressed-Distributed Interactive Simulation protocol.

The gateway encodes/decodes DIS PDUs to/from C-DIS.
"""
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/zlubsen/dis-rs"
categories = ["network-programming"]
keywords = ["simulation", "DIS", "C-DIS", "gateway", "CLI"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
async-stream = "0.3.5"
axum = { version = "0.7.5", features = ["tokio", "http2"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
bytes = "1.4.0"
bytesize = "1.3.0"
cdis-assemble = { path = "../cdis-assemble" }
clap = { version = "4.5.4", features = ["derive"] }
clap_derive = "4.2.0"
dis-rs = { path = "../dis-rs" }
futures = "0.3.30"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
tokio = { version = "1.28.1", features = ["full"] }
tokio-stream = "0.1.15"
toml = "0.7.3"
tower-http = { version = "0.5.0", features = ["fs", "trace"] }
serde = "1.0.163"
serde_derive = "1.0.163"
socket2 = "0.5.3"
